#配置服务名称
spring:
  application:
    name: product-service
  #配置数据库
  datasource:
    url: jdbc:mysql://47.95.212.30:3306?shellmall?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 101396
    type: com.zaxxer.hikari.HikariDataSource
#配置端口
server:
  port: 8200
#配置mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.huatech.mall.service.entity
  mapper-locations: classpath:mapper/*/*.xml

#配置数据库查询插件
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSq

